Test migration
charlesleezhaoyi/project3-backend-bootcamp pull request #3
Opened 2024-03-20 07:22 UTC by Qiannnly

1) Added all migration files except user and category which Charles already created
2) Populated 3 rows to Books table
3) Implemented post router and controller for "books" table to insert one book

2024-03-20 09:14 UTC, Qiannnly commented on db/models/donation.js
Since "donations" is a M-M relationship between "users" and "books", this model should be removed.

2024-03-20 11:02 UTC, ianlauyin requested changes

2024-03-20 11:02 UTC, ianlauyin commented on controllers/booksController.js
> +    const { title, author, description, released_year, condition, review } =
released_year should be releasedYear when passing data from FE API, It's strange to pass snakecase code to BE suddenly.

2024-03-20 11:02 UTC, ianlauyin commented on controllers/booksController.js
> +      });
You can just pass req.body to the model.create, because it's the same data.
Also, you can pass releasedYear to the SQL database becauser you have defined underscored=True, It will automictically change camelCase to snake_case in the model method.

2024-03-20 11:02 UTC, ianlauyin commented on db/migrations/20240319131451-create-photo.js
> +      },
Missing reference for book id

2024-03-20 11:02 UTC, ianlauyin commented on db/migrations/20240319131604-create-donation.js
> +      },
Missing reference of donor, book and bene id

2024-03-20 11:02 UTC, ianlauyin commented on db/migrations/20240319131827-create-request.js
> +        type: Sequelize.INTEGER
missing donation reference

2024-03-20 11:02 UTC, ianlauyin commented on db/migrations/20240319131827-create-request.js
> +        type: Sequelize.INTEGER
Missing bene reference

2024-03-20 11:02 UTC, ianlauyin commented on db/migrations/20240319131827-create-request.js
> +      },
Use type enums copy from the model. 
I think currently is "pending", "accepted" , "rejected" , "cancelled", and “collected”

2024-03-20 11:02 UTC, ianlauyin commented on db/models/book.js
> +      this.hasMany(models.donation);
Can add belongsToMany to and model.user through models.donation

2024-03-20 11:02 UTC, ianlauyin commented on db/models/donation.js
user and donation also contains a M-M relationship through request, I think it's better have a donation table also.

2024-03-20 11:02 UTC, ianlauyin commented on db/models/donation.js
> +      this.hasMany(models.request);
Can also add belongsToMany with models.user through request

2024-03-20 11:23 UTC, ianlauyin requested changes

2024-03-20 11:23 UTC, ianlauyin commented on db/models/user.js
> +      this.hasMany(models.donation);
Add this.belongsToMany  to book as donor and bene through donation
add this.belongsToMany  to donation throught request

2024-03-21 04:51 UTC, ianlauyin approved these changes
Generally, it's okay. But you will face bug eventually if you keep working on the these model setting. But it's okay to fix it in later time.

2024-03-21 04:51 UTC, ianlauyin commented on db/migrations/20240319131604-create-donation.js
> +      },
Sorry to miss that, bene_id should have allowNull=true

2024-03-21 04:51 UTC, ianlauyin commented on db/models/comment.js
> +      this.belongsTo(models.user, { as: "user", foreignKey: "userId" });
Why changing the comment model? It's unnessary to use as and foreignKey if there are not alias.

```suggestion
      this.belongsTo(models.post);
      this.belongsTo(models.user);
```

2024-03-21 04:51 UTC, ianlauyin commented on db/models/donation.js
> +      this.belongsTo(models.user, { as: "donor" });
Should add foreignKey = beneId and donorId

2024-03-21 04:51 UTC, ianlauyin commented on db/models/donation.js
> +      // this.belongsTo(models.book);
Why comment it out?

2024-03-21 04:51 UTC, ianlauyin commented on db/models/request.js
> +      this.belongsTo(models.donation, { as: "bene", foreignKey: "beneId" });
```suggestion
      this.belongsTo(models.donation);
```

2024-03-21 04:51 UTC, ianlauyin commented on db/models/photo.js
> +      this.belongsTo(models.book, { as: "book", foreignKey: "bookId" });
```suggestion
      this.belongsTo(models.book);
```

2024-03-21 04:51 UTC, ianlauyin commented on db/models/user.js
> +      this.belongsToMany(models.book, { as: "bene", through: "donation" });
I think you should add foreignKey= donorId and beneId

2024-03-21 04:51 UTC, ianlauyin commented on db/models/user.js
> +      this.belongsToMany(models.donation, { through: "request" });
I think you should add foreignKey=beneId

2024-03-21 13:31 UTC, merged